// src/data/useCaseData.js

export const appData = [
  {
    id: "cmss", 
    title: "CMSS (Communication Meteo Switching System)",
    description: "CMSS (Communication Meteo Switching System) adalah sistem perangkat lunak yang berfungsi sebagai gerbang utama pertukaran data meteorologi di BMKG. Sistem ini bekerja sebagai Message Switching yang menghubungkan stasiun daerah dengan jaringan Global Telecommunication System (GTS).",
    logoUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/logo-cmss.png",  
    diagramUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/CMSS.drawio.png",
  },
  {
    id: "ekinerja",
    title: "E-Kinerja",
    description: "Aplikasi ini digunakan untuk mencatat rencana kerja (SKP), aktivitas harian (Logbook), dan penilaian prestasi pegawai.",
    logoUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/logo-ekinerja.png",
    diagramUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/E-Kinerja.drawio.png",
  },
  {
    id: "eoffice",
    title: "E-Office BMKG",
    description: "Aplikasi ini fokus pada pengelolaan persuratan dinas (Tata Naskah Dinas Elektronik) secara digital.",
    logoUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/eoffice.png",
    diagramUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/E-Office%20BMKG.drawio.png",
  },
  {
    id: "soft",
    title: "BMKGSoft",
    description: "Aplikasi ini berfungsi menggantikan pencatatan manual (Buku ME-48), melakukan perhitungan parameter cuaca secara otomatis (koreksi barometer, kelembaban, dll), serta mengubah data menjadi format sandi baku (SYNOP, METAR) sebelum dikirimkan melalui sistem CMSS.",
    logoUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/logobmkg.png",
    diagramUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/use-case-bmkgsoft.png",
  },
  {
    id: "syn",
    title: "Synergy",
    description: "Aplikasi ini digunakan sebagai alat bantu analisis meteorologi untuk menyusun berbagai produk layanan cuaca, antara lain pembuatan prakiraan cuaca, penyusunan produk penerbangan, dan analisis data satelit & radar",
    logoUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/logobmkg.png",
    diagramUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/use-case-synergie.png",
  },
  {
    id: "nowcasting",
    title: "Nowcasting",
    description: "Aplikasi ini digunaakan untuk peringatan dini cuaca jangka sangat pendek yang digunakan oleh unit Data dan Informasi (Datin) untuk mendeteksi potensi cuaca ekstrem.",
    logoUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/logobmkg.png",
    diagramUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/UC%20NOWCASTING.png",
  },
  {
    id: "sapk",
    title: "MY SAPK BKN",
    description: "Aplikasi  dari BKN untuk memudahkan PNS mengakses data kepegawaian, layanan, hingga pemutakhiran data mandiri secara daring, mencakup profil PNS, KPE Virtual, notifikasi layanan kenaikan pangkat/pensiun, serta data pendukung lainnya seperti BPJS dan Taspen, demi menciptakan data kepegawaian nasional yang lebih akurat. ",
    logoUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/logo-sapk-bkn.png",
    diagramUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/use-case-my-sapk-bkn.png",
  },
  {
    id: "sakti",
    title: "SAKTI (Sistem Aplikasi Keuangan Tingkat Instansi)",
    description: "Aplikasi terintegrasi dari Kementerian Keuangan untuk mengelola seluruh siklus keuangan negara bagi Satuan Kerja (Satker) pemerintah, mencakup perencanaan, pelaksanaan, hingga pertanggungjawaban anggaran secara digital, mengintegrasikan semua modul keuangan dalam satu sistem dengan konsep single database dan single entry point untuk meningkatkan efisiensi, transparansi, dan akuntabilitas pengelolaan APBN. ",
    logoUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/logosakti.png",
    diagramUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/SAKTI.drawio.png",
  },
  {
    id: "saiba",
    title: "SAIBA (Sistem Akuntansi Instansi)",
    description: "Aplikasi  dari BKN untuk memudahkan PNS mengakses data kepegawaian, layanan, hingga pemutakhiran data mandiri secara daring, mencakup profil PNS, KPE Virtual, notifikasi layanan kenaikan pangkat/pensiun, serta data pendukung lainnya seperti BPJS dan Taspen, demi menciptakan data kepegawaian nasional yang lebih akurat. ",
    logoUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/logosaibe.jpg",
    diagramUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/SAKTI.drawio.png",
  },
  {
    id: "simakbmn",
    title: "SIMAK-BMN (Sistem Informasi Manajemen dan Akuntansi Barang Milik Negara)",
    description: "Aplikasi terpadu dari Kementerian Keuangan untuk mengelola, mencatat, dan melaporkan seluruh siklus hidup Barang Milik Negara (BMN) di instansi pemerintah, mulai dari pengadaan, mutasi, hingga penghapusan untuk mendukung penyusunan laporan keuangan yang akuntabel dan akurat melalui proses komputarisasi data aset negara.",
    logoUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/logo-simak-bmn.png",
    diagramUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/use-case-simak-bmn.drawio.png",
  },
  {
    id: "sprint",
    title: "SPRINT (Sistem Pengelolaan Rekening Terintegrasi)",
    description: "Aplikasi SPRINT adalah aplikasi yang digunakan untuk menatausahakan rekening pemerintah baik rekening pengeluaran, penerimaan maupun rekening lainnya. Aplikasi ini terintegrasi dengan sistem perbankan dan juga digunakan untuk melakukan pelaporan pertanggungjawaban rekening pemerintah",
    logoUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/logo-sprint.png",
    diagramUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/SPRINT.drawio.png",
  },
  {
    id: "siman",
    title: "SIMAN (Sistem Informasi Manajemen Aset Negara)",
    description: "Aplikasi digital dari Kementerian Keuangan (DJKN) untuk mengelola seluruh siklus Barang Milik Negara (BMN) secara terintegrasi dan transparan, mulai dari perencanaan hingga penghapusan.",
    logoUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/logo-siman.png",
    diagramUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/use-case-siman.png",
  },
  {
    id: "sippb",
    title: "SIPPB (Sistem Informasi Perencanaan dan Penganggaran BMKG)",
    description: "Aplikasi berbasis web yang dikembangkan oleh BMKG Pusat untuk memfasilitasi proses penyusunan, penelaahan, dan penetapan rencana kerja serta anggaran tahunan di seluruh satuan kerja (stasiun) BMKG.",
    logoUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/logobmkg.png",
    diagramUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/use-case-sippb.png",
  },
  {
    id: "spreso",
    title: "SPRESO (Sistem Presensi Online)",
    description: "Aplikasi ini adalah backend (sistem pusat) yang mengolah data kehadiran pegawai untuk menentukan besaran uang Tunjangan Kinerja (Tukin) dan Uang Makan yang akan diterima setiap bulan.",
    logoUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/logo-espreso.jpeg",
    diagramUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/use-case-spreso.png",
  },
  {
    id: "simas",
    title: "SIMAS (Sistem Informasi Manajemen Aparatur Sipil Negara)",
    description: "Aplikasi berbasis web yang berfungsi untuk mengelola data kepegawaian secara internal. Sistem ini dirancang untuk mengotomatisasi proses bisnis pengelolaan SDM di lingkungan BMKG, melengkapi aplikasi nasional seperti MyASN (BKN).",
    logoUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/00%20Logo%202a.png",
    diagramUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/use-case-simas.png",
  },
  {
    id: "info",
    title: "Info BMKG",
    description: "Aplikasi pengawasan yang digunakan untuk memastikan seluruh peralatan operasional meteorologi dan infrastruktur jaringan berfungsi dengan baik secara real-time.",
    logoUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/logobmkg.png",
    diagramUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/monitoring%20(1).png",
  },
  {
    id: "gpp",
    title: "GPP (Gaji PNS Pusat)",
    description: "Aplikasi untuk menghitung berapa rupiah gaji yang akan diterima pegawai sebelum datanya dikirim ke SAKTI untuk dibayar.",
    logoUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/logo-gpp.png",
    diagramUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/GPP.drawio.png",
  },
  {
    id: "wigos",
    title: "WIGOS (WMO Integrated Global Observing System)",
    description: "Aplikasi dengan integrasi global yang dikembangkan oleh Organisasi Meteorologi Dunia (WMO) untuk menyatukan seluruh sistem pengamatan cuaca, iklim, dan hidrologi dari berbagai negara anggota ke dalam satu kerangka kerja yang terstandarisasi.",
    logoUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/logobmkg.png",
    diagramUrl: "https://hfctpsuwjytwyhrdoggb.supabase.co/storage/v1/object/public/usecase/UC%20WIGOS.png",
  },
  
];