import React from 'react';
import './css/TechnologyAppMatrix.css'; // Import CSS terpisah

const TechnologyAppMatrix = () => {
  // 1. Data Aplikasi (Kolom)
  const applications = [
    { id: 'app1', name: 'Sistem Kepegawaian (HRIS)' },
    { id: 'app2', name: 'E-Budgeting' },
    { id: 'app3', name: 'Website Publik' },
    { id: 'app4', name: 'Aplikasi Aset (E-Asset)' },
  ];

  // 2. Data Teknologi (Baris) - Dikelompokkan biar rapi ala EA
  const technologies = [
    { id: 'tech1', category: 'Server (Physical)', name: 'Server Blade Dell R740' },
    { id: 'tech2', category: 'OS Platform', name: 'Red Hat Enterprise Linux 8' },
    { id: 'tech3', category: 'OS Platform', name: 'Windows Server 2019' },
    { id: 'tech4', category: 'Database', name: 'Oracle Database 19c' },
    { id: 'tech5', category: 'Database', name: 'PostgreSQL' },
    { id: 'tech6', category: 'Middleware', name: 'Apache Tomcat' },
    { id: 'tech7', category: 'Network', name: 'Firewall Fortigate' },
  ];

  // 3. Data Hubungan/Relasi (Mapping)
  // Format: "Key" gabungan ID Tech & App, Value: Tipe hubungan
  const matrixData = {
    'tech1-app1': 'Hosting',
    'tech1-app2': 'Hosting',
    'tech2-app1': 'OS',
    'tech2-app2': 'OS',
    'tech2-app3': 'OS',
    'tech3-app4': 'OS',
    'tech4-app1': 'Primary DB',
    'tech4-app2': 'Primary DB',
    'tech5-app3': 'DB',
    'tech5-app4': 'DB',
    'tech6-app3': 'App Server',
    'tech7-app3': 'Security',
  };

  // Helper untuk mengecek isi sel
  const getCellContent = (techId, appId) => {
    const key = `${techId}-${appId}`;
    return matrixData[key] || '';
  };

  return (
    <div className="idea-container">
      <div className="idea-header">
        <h2 className="idea-title">Matriks Aplikasi & Teknologi (Technology Application Matrix)</h2>
        <p className="idea-subtitle">Dokumen Arsitektur Teknologi - Peta Hubungan Infrastruktur</p>
      </div>

      <div className="idea-table-wrapper">
        <table className="idea-table">
          <thead>
            <tr>
              <th className="th-tech-header" colSpan="2">Komponen Teknologi</th>
              {applications.map((app) => (
                <th key={app.id} className="th-app-header">
                  {app.name}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {technologies.map((tech) => (
              <tr key={tech.id}>
                <td className="td-category">{tech.category}</td>
                <td className="td-tech-name">{tech.name}</td>
                {applications.map((app) => {
                  const content = getCellContent(tech.id, app.id);
                  return (
                    <td 
                      key={app.id} 
                      className={`td-cell ${content ? 'active-cell' : ''}`}
                    >
                      {content && <span className="relationship-tag">{content}</span>}
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      
      <div className="idea-footer">
        <p>Generated by Enterprise Architecture System</p>
      </div>
    </div>
  );
};

export default TechnologyAppMatrix;